version: "3.3"

services:
    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: local.Nginx.Dockerfile
        ports:
            - 80:80
        environment:
            - NGINX_HOST=local.what-to-wear.ru
            - NGINX_PORT=80
        links:
            - php
        volumes:
            - ./www:/var/www
            - ./logs:/var/log/nginx
    php:
        restart: unless-stopped
        build:
            context: .
            dockerfile: local.php.Dockerfile
        volumes:
            - ./www:/var/www
        links:
            - db
    db:
        image: mysql:5.7
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=what-to-wear.ru
        volumes:
            - ./mysql-data:/var/lib/mysql